version: '3.8'

services:
  fcircle:
    image: txm123/fcircle:latest
    container_name: fcircle
    restart: always
    ports:
      - "8521:8080"
    volumes:
      - ./logs:/app/output
    environment:
      - SERVER_PORT=8080                     # 对应 容器启动端口
      - INTERVAL_HOURS=6                    # 设置定时调用的间隔时间
      - CONFIG_URL=https://source.adoreorg.cn/json/RSS.json  # 配置文件url
      - OUTPUT_FILE=output/feed_result.json   # 朋友圈json文件路径
      - LOG_FILE=output/crawl.log   # 日志文件路径
